version:
  "3.8"

services:
  ######
  # PROD
  ######
  postgres-prod:
    image: postgres:14.0
    container_name: "pgsql.prod"
    environment:
      POSTGRES_DB: 'dnevnik_rg'
      POSTGRES_USER: 'dnevnik_rg_user_prod'
      POSTGRES_PASSWORD: 'NDY1Yzg2YjQtNDQzMy00OWQzLTkxODgtMGNkNmQ3Nzc4MmMx'
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schemas.sql
      - ./flyway/sql:/flyway/sql
    command: [ "docker-entrypoint.sh", "postgres" ]
    ports:
      - "5588:5432"
  flyway-prod:
    image: flyway/flyway:10.11
    depends_on:
      - postgres-prod
    volumes:
      - ./migrations/prod/sql:/flyway/sql
    env_file:
      - ./migrations/prod/env/.env
    environment:
      - FLYWAY_LOCATIONS="filesystem:/flyway/sql"
    entrypoint: [ "sh", "-c", "/flyway/flyway -url=jdbc:postgresql://pgsql.prod:5432/dnevnik_rg -user=dnevnik_rg_user_prod -password=NDY1Yzg2YjQtNDQzMy00OWQzLTkxODgtMGNkNmQ3Nzc4MmMx -locations=filesystem:/flyway/sql -connectRetries=3 migrate" ]