version:
  "3.8"

services:
  postgres-prod:
    build:
      context: .
      dockerfile: Dockerfile-prod-sql
    image: postgres:latest
    container_name: "dnevnik-rg-prod-db"
    environment:
      POSTGRES_DB: 'dnevnik_rg'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5588:5432"

  flyway-prod:
    container_name: "flyway.prod"
    build:
      context: .
      dockerfile: Dockerfile-prod-flyway
    depends_on:
      - postgres-prod
    image: flyway/flyway:10.11
    env_file:
      - ./migrations/prod/env/.env
    environment:
      - FLYWAY_LOCATIONS="filesystem:/flyway/sql"
    entrypoint: [ "sh", "-c", "/flyway/flyway -url=jdbc:postgresql://dnevnik-rg-prod-db:5432/dnevnik_rg -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql -connectRetries=3 migrate" ]