version:
  "3.8"

services:
  #######
  # STAGE
  #######
  postgres-stage:
    image: postgres:14.0
    container_name: "pgsql.stage"
    environment:
      POSTGRES_DB: 'dnevnik_rg'
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schemas.sql
      - ./flyway/sql:/flyway/sql
    command: [ "docker-entrypoint.sh", "postgres" ]
    ports:
      - "5589:5432"
  flyway-stage:
    image: flyway/flyway:10.11
    depends_on:
      - postgres-stage
    volumes:
      - ./migrations/stage/sql:/flyway/sql
    env_file:
      - ./migrations/stage/env/.env
    environment:
      - FLYWAY_LOCATIONS="filesystem:/flyway/sql"
    entrypoint: [ "sh", "-c", "/flyway/flyway -url=jdbc:postgresql://pgsql.stage:5432/dnevnik_rg -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql -connectRetries=3 migrate" ]
