version:
  "3.8"

services:
  postgres-stage:
    build:
      context: .
      dockerfile: Dockerfile-stage-sql
    image: postgres:latest
    container_name: "dnevnik-rg-stage-db"
    environment:
      POSTGRES_DB: 'dnevnik_rg'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5589:5432"

  flyway-stage:
    container_name: "flyway.stage"
    build:
      context: .
      dockerfile: Dockerfile-stage-flyway
    image: flyway/flyway:10.11
    depends_on:
      - postgres-stage
    env_file:
      - ./migrations/.env.stage
    environment:
      - FLYWAY_LOCATIONS="filesystem:/flyway/sql"
    entrypoint: [ "sh", "-c", "/flyway/flyway -url=jdbc:postgresql://dnevnik-rg-stage-db:5432/dnevnik_rg -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql -connectRetries=3 migrate" ]
